apiVersion: v1
kind: Secret
metadata:
  name: certverify-secrets
type: Opaque
stringData:
  DB_NAME: certverify_db
  DB_USER: certuser
  DB_PASSWORD: certpass123
  DB_HOST: mysql-service
  DB_PORT: "3306"
  ALLOWED_HOSTS: "localhost,127.0.0.1,backend,frontend-service"
  DJANGO_SECRET_KEY: "certverify-secret-key-blockchain-2024"
  DEBUG: "False"
  CONTRACT_ADDRESS: "0x0E92A994BfBb9b7fA0886cF036A78785969c0B09"
  SEPOLIA_RPC_URL: "https://sepolia.infura.io/v3/3ee8667eb2a94bc7b4b7074cd44299e8"